const std = @import("std");
const c = @cImport({
    @cInclude("stdio.h");
});
const CONF = @import("../engine/config.zig").CONF;
const project_mod = @import("project.zig");
const Project = project_mod.Project;
const Image = project_mod.Image;
const Map = project_mod.Map;
const PaletteColor = project_mod.PaletteColor;

const DATA_INC_PATHS = [_][*:0]const u8{
    "GAMEBOY-ENGINE/SRC/data.inc",
    "../GAMEBOY-ENGINE/SRC/data.inc",
    "../../GAMEBOY-ENGINE/SRC/data.inc",
    "../../../GAMEBOY-ENGINE/SRC/data.inc",
};
const PALETTE_INC_PATHS = [_][*:0]const u8{
    "GAMEBOY-ENGINE/SRC/palette.inc",
    "../GAMEBOY-ENGINE/SRC/palette.inc",
    "../../GAMEBOY-ENGINE/SRC/palette.inc",
    "../../../GAMEBOY-ENGINE/SRC/palette.inc",
};
const LEVEL_INC_PATHS = [_][*:0]const u8{
    "GAMEBOY-ENGINE/SRC/level.inc",
    "../GAMEBOY-ENGINE/SRC/level.inc",
    "../../GAMEBOY-ENGINE/SRC/level.inc",
    "../../../GAMEBOY-ENGINE/SRC/level.inc",
};

const BG_TILE_BASE: u8 = 6;
const ENGINE_MAP_W: u16 = 32;
const ENGINE_MAP_H: u16 = 32;
const MAX_BG_TILES: u16 = 256 - @as(u16, BG_TILE_BASE);

const ExportLevel = struct {
    label: []const u8,
    bank_id: u8,
};

const LEVELS = [_]ExportLevel{
    .{ .label = "GrasslandLevel", .bank_id = 0 },
    .{ .label = "DesertLevel", .bank_id = 1 },
};

pub fn exportGameBoyEngine(project: *const Project) !void {
    try writeSpritePalettes(project);
    try writeSpriteTiles(project);
    try writeLevels(project);
}

fn writeSpritePalettes(project: *const Project) !void {
    var writer = try CWriter.createFirst(&DATA_INC_PATHS);
    defer writer.close();

    try writer.writeAll("; This file is generated by P1Xel Editor. Do not edit by hand.\n");
    try writer.writeAll("; CGB object palettes, 8 palettes x 4 colors, RGBDS DW little-endian.\n\n");
    try writer.writeAll("; ======================================> GAME DATA <=======================|80|\n");
    try writer.writeAll("SpritesPalettes:\n");
    try writePaletteWords(writer, project, .sprites, project.activePaletteBank());
    try writer.writeAll("SpritesPalettesEnd:\n");
}

fn writeSpriteTiles(project: *const Project) !void {
    var writer = try CWriter.createFirst(&PALETTE_INC_PATHS);
    defer writer.close();

    try writer.writeAll("; This file is generated by P1Xel Editor. Do not edit by hand.\n");
    try writer.print("; First {d} OBJ tiles are loaded before BG tiles start at tile {d}.\n\n", .{ BG_TILE_BASE, BG_TILE_BASE });
    try writer.writeAll("GameTiles:\n");

    const sprite_count = project.imageCountMode(.sprites);
    var i: u16 = 0;
    while (i < BG_TILE_BASE) : (i += 1) {
        const image = if (i < sprite_count) project.imageAtMode(.sprites, i) else blankImage();
        try writer.print("; OBJ tile {d}\n", .{i});
        try writeTile2bpp(writer, image);
    }

    try writer.writeAll("GameTilesEnd:\n");
    try writer.writeAll("; ==========================================================================|80|\n");
}

fn writeLevels(project: *const Project) !void {
    var writer = try CWriter.createFirst(&LEVEL_INC_PATHS);
    defer writer.close();

    try writer.writeAll("; This file is generated by P1Xel Editor. Do not edit by hand.\n");
    try writer.writeAll("; The current engine loads one 32x32 CGB BG map at _SCRN0.\n");
    try writer.writeAll("; Editor maps are exported into that hardware map, cropped/padded as needed.\n\n");
    try writer.print("DEF LEVEL_MAP_WIDTH_TILES EQU {d}\n", .{ENGINE_MAP_W});
    try writer.print("DEF LEVEL_MAP_HEIGHT_TILES EQU {d}\n", .{ENGINE_MAP_H});
    try writer.print("DEF LEVEL_BG_TILE_BASE EQU {d}\n\n", .{BG_TILE_BASE});

    for (LEVELS) |level| {
        try writeLevel(writer, project, level);
        try writer.writeAll("\n");
    }
}

fn writeLevel(writer: anytype, project: *const Project, level: ExportLevel) !void {
    const map = project.mapAtBank(level.bank_id);
    const tile_count = @min(project.imageCountMode(.tiles), MAX_BG_TILES);

    try writer.print("DEF {s}_WIDTH_TILES EQU {d}\n", .{ upperLabel(level.label), map.width });
    try writer.print("DEF {s}_HEIGHT_TILES EQU {d}\n", .{ upperLabel(level.label), map.height });
    try writer.print("DEF {s}_BG_TILE_COUNT EQU {d}\n\n", .{ upperLabel(level.label), tile_count });

    try writer.print("{s}Tiles:\n", .{level.label});
    var tile_id: u16 = 0;
    while (tile_id < tile_count) : (tile_id += 1) {
        try writer.print("; BG tile {d} -> VRAM tile {d}\n", .{ tile_id, tile_id + BG_TILE_BASE });
        try writeTile2bpp(writer, project.imageAtMode(.tiles, tile_id));
    }
    try writer.print("{s}TilesEnd:\n\n", .{level.label});

    try writer.print("{s}TileMap:\n", .{level.label});
    try writeTileMap(writer, map, tile_count);
    try writer.print("{s}TileMapEnd:\n\n", .{level.label});

    try writer.print("{s}AttrMap:\n", .{level.label});
    try writeAttrMap(writer, map);
    try writer.print("{s}AttrMapEnd:\n\n", .{level.label});

    try writer.print("{s}BgPalettes:\n", .{level.label});
    try writePaletteWords(writer, project, .tiles, level.bank_id);
    try writer.print("{s}BgPalettesEnd:\n\n", .{level.label});

    try writer.print("{s}Descriptor:\n", .{level.label});
    try writer.print("    DW {s}BgPalettes, {s}BgPalettesEnd\n", .{ level.label, level.label });
    try writer.print("    DW {s}Tiles, {s}TilesEnd\n", .{ level.label, level.label });
    try writer.print("    DW {s}TileMap, {s}TileMapEnd\n", .{ level.label, level.label });
    try writer.print("    DW {s}AttrMap, {s}AttrMapEnd\n", .{ level.label, level.label });
}

fn writeTileMap(writer: anytype, map: *const Map, tile_count: u16) !void {
    const fill = BG_TILE_BASE;
    var y: u16 = 0;
    while (y < ENGINE_MAP_H) : (y += 1) {
        try writer.writeAll("    DB ");
        var x: u16 = 0;
        while (x < ENGINE_MAP_W) : (x += 1) {
            const value: u8 = if (x < map.width and y < map.height) value: {
                const idx = @as(usize, y) * @as(usize, map.width) + x;
                const safe_id = @min(@as(u16, map.tile_ids[idx]), tile_count -| 1);
                break :value @intCast(safe_id + BG_TILE_BASE);
            } else fill;
            if (x != 0) try writer.writeAll(",");
            try writer.print("${X:0>2}", .{value});
        }
        try writer.writeAll("\n");
    }
}

fn writeAttrMap(writer: anytype, map: *const Map) !void {
    var y: u16 = 0;
    while (y < ENGINE_MAP_H) : (y += 1) {
        try writer.writeAll("    DB ");
        var x: u16 = 0;
        while (x < ENGINE_MAP_W) : (x += 1) {
            const value: u8 = if (x < map.width and y < map.height) value: {
                const idx = @as(usize, y) * @as(usize, map.width) + x;
                break :value map.tile_attrs[idx];
            } else 0;
            if (x != 0) try writer.writeAll(",");
            try writer.print("${X:0>2}", .{value});
        }
        try writer.writeAll("\n");
    }
}

fn writePaletteWords(writer: anytype, project: *const Project, mode: project_mod.ProjectMode, bank_id: u8) !void {
    for (0..CONF.PALETTE_COUNT) |palette_id| {
        try writer.writeAll("    DW ");
        for (0..CONF.COLORS_PER_PALETTE) |color_id| {
            const rgb = project.paletteColorAtBankMode(mode, bank_id, @intCast(palette_id), @intCast(color_id));
            if (color_id != 0) try writer.writeAll(",");
            try writer.print("${X:0>4}", .{gbcColor(rgb)});
        }
        try writer.writeAll("\n");
    }
}

fn writeTile2bpp(writer: anytype, image: Image) !void {
    var row: usize = 0;
    while (row < CONF.TILE_SIDE) : (row += 1) {
        var lo: u8 = 0;
        var hi: u8 = 0;
        var col: usize = 0;
        while (col < CONF.TILE_SIDE) : (col += 1) {
            const px = image.pixels[row * CONF.TILE_SIDE + col] & 3;
            const bit: u3 = @intCast(7 - col);
            lo |= (px & 1) << bit;
            hi |= ((px >> 1) & 1) << bit;
        }
        try writer.print("    DB ${X:0>2},${X:0>2}\n", .{ lo, hi });
    }
}

fn gbcColor(rgb: PaletteColor) u16 {
    const r: u16 = @as(u16, rgb[0] >> 3);
    const g: u16 = @as(u16, rgb[1] >> 3);
    const b: u16 = @as(u16, rgb[2] >> 3);
    return r | (g << 5) | (b << 10);
}

fn blankImage() Image {
    return .{};
}

fn upperLabel(label: []const u8) []const u8 {
    if (std.mem.eql(u8, label, "GrasslandLevel")) return "GRASSLANDLEVEL";
    if (std.mem.eql(u8, label, "DesertLevel")) return "DESERTLEVEL";
    return label;
}

const CWriter = struct {
    file: *c.FILE,

    fn createFirst(paths: []const [*:0]const u8) !CWriter {
        for (paths) |path| {
            if (c.fopen(path, "wb")) |file| return .{ .file = file };
        }
        return error.ExportFailed;
    }

    fn close(self: *CWriter) void {
        _ = c.fclose(self.file);
    }

    pub fn writeAll(self: *const CWriter, bytes: []const u8) !void {
        if (bytes.len == 0) return;
        if (c.fwrite(bytes.ptr, 1, bytes.len, self.file) != bytes.len) return error.ExportFailed;
    }

    pub fn print(self: *const CWriter, comptime fmt: []const u8, args: anytype) !void {
        var buf: [512]u8 = undefined;
        const text = std.fmt.bufPrint(&buf, fmt, args) catch return error.ExportFailed;
        try self.writeAll(text);
    }
};
