const THE_NAME = "P1Xel Editor";
const SCREEN_W = 1024;
const SCREEN_H = 640;

const PIVOT_PADDING = 24;
const PIVOT_TL_X = PIVOT_PADDING;
const PIVOT_TL_Y = PIVOT_PADDING;
const PIVOT_TR_X = SCREEN_W - PIVOT_PADDING;
const PIVOT_TR_Y = PIVOT_PADDING;
const PIVOT_BL_X = PIVOT_PADDING;
const PIVOT_BL_Y = SCREEN_H - PIVOT_PADDING;
const PIVOT_BR_X = SCREEN_W - PIVOT_PADDING;
const PIVOT_BR_Y = SCREEN_H - PIVOT_PADDING;

const MAX_PALETTES = 100;
